import React from 'react';
import Head from 'next/head';

/**
 * This is the home page!
 * @returns {JSX.Element}: The JSX Code for home page.
 */

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>NextJS Boilerplate</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div
        style={{
          height: '100vh',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <p>Hello World!</p>
      </div>
    </>
  );
}
